# Generated by Django 5.2.7 on 2025-10-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='service',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='portal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanel.portal'),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='sector',
            field=models.TextField(blank=True),
        ),
    ]
