# Generated by Django 5.2.7 on 2025-10-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_travelbooking_service_alter_travelbooking_portal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbooking',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanel.portal'),
        ),
    ]
